"""rename address

Revision ID: a10e41f0d114
Revises: d6855ae87d60
Create Date: 2025-12-28 15:34:47.954085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10e41f0d114'
down_revision = 'd6855ae87d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')

    # ### end Alembic commands ###
