"""rename department

Revision ID: d6855ae87d60
Revises: 5ebd219f93ab
Create Date: 2025-12-28 15:01:02.585998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6855ae87d60'
down_revision = '5ebd219f93ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
